<?php
/**
 * Created by PhpStorm.
 * User: Nguyen Tuan Linh
 * Date: 2015-12-06
 * Time: 19:13
 */

return [
    'file_url' => env('FILE_URL', ''),
    'file_path' => env('FILE_PATH', ''),
    'home_cookie_domain' => env('HOME_COOKIE_DOMAIN', '.antoree.com'),
    'home_cookie_lifetime' => env('HOME_COOKIE_LIFETIME', 0),
    'home_cookie_name' => env('HOME_COOKIE_NAME', 'antoree'),
    'home_cookie_original_name' => env('HOME_COOKIE_ORIGINAL_NAME', 'antoree_origin'),
    'home_cookie_settings_name' => env('HOME_COOKIE_SETTINGS_NAME', 'antoree_settings'),
    'extra_removing_cookies' => env('EXTRA_REMOVING_COOKIES', ''),
    'home_encrypt_secret' => env('HOME_ENCRYPT_SECRET', ''),

    'app' => [
        'description' => env('APP_DESCRIPTION', ''),
        'keywords' => env('APP_KEYWORDS', ''),
        'short_name' => env('APP_SHORT_NAME', ''),
        'version' => env('APP_VERSION', ''),
        'author' => env('APP_AUTHOR', ''),
        'email' => env('APP_EMAIL', ''),
        'logo' => env('APP_LOGO', ''),
        'default_user_picture' => env('APP_DEFAULT_USER_PICTURE', ''),
    ],

    'settings' => [
        'city' => 'LA',
        'country' => 'US',
        'currency' => 'USD',
        'number_format' => 'point_comma',
        'first_day_of_week' => 0,
        'long_date_format' => 0,
        'short_date_format' => 0,
        'long_time_format' => 0,
        'short_time_format' => 0,
    ],

    'idle_switching_time' => 120, // seconds

    'theme_from_db' => false,
    'admin_theme' => Katniss\Everdeen\Themes\AdminThemes\AdminLte\Theme::NAME,
    'admin_themes' => [
        Katniss\Everdeen\Themes\AdminThemes\AdminLte\Theme::NAME => Katniss\Everdeen\Themes\AdminThemes\AdminLte\Theme::class,
    ],
    'admin_except_themes' => [
    ],
    'home_theme' => Katniss\Everdeen\Themes\HomeThemes\ExampleTheme\Theme::NAME,
    'home_themes' => [
        Katniss\Everdeen\Themes\HomeThemes\ExampleTheme\Theme::NAME => Katniss\Everdeen\Themes\HomeThemes\ExampleTheme\Theme::class,
    ],
    'home_except_themes' => [
    ],
    'extensions' => [
    ],
    'static_extensions' => [
    ],
    'admin_except_extensions' => [
    ],
    'paths_use_admin_theme' => [
        'admin', 'auth', 'documents', 'password', 'me'
    ],

    'genders' => [
        'male', 'female', 'other'
    ],

    'number_formats' => [
        'point_comma',
        'point_space',
        'comma_point',
        'comma_space',
    ],

    'currencies' => [
        'USD' => ['name' => 'U.S. Dollar', 'symbol' => '$'],
        'VND' => ['name' => 'Vietnam Dong', 'symbol' => '₫'],
    ],

    'locales' => [
        'ace' => ['name' => 'Achinese', 'script' => 'Latn', 'native' => 'Aceh', 'regional' => ''],
        'af' => ['name' => 'Afrikaans', 'script' => 'Latn', 'native' => 'Afrikaans', 'regional' => 'af_ZA'],
        'agq' => ['name' => 'Aghem', 'script' => 'Latn', 'native' => 'Aghem', 'regional' => ''],
        'ak' => ['name' => 'Akan', 'script' => 'Latn', 'native' => 'Akan', 'regional' => 'ak_GH'],
        'an' => ['name' => 'Aragonese', 'script' => 'Latn', 'native' => 'aragonés', 'regional' => 'an_ES'],
        'cch' => ['name' => 'Atsam', 'script' => 'Latn', 'native' => 'Atsam', 'regional' => ''],
        'gn' => ['name' => 'Guaraní', 'script' => 'Latn', 'native' => 'Avañe’ẽ', 'regional' => ''],
        'ae' => ['name' => 'Avestan', 'script' => 'Latn', 'native' => 'avesta', 'regional' => ''],
        'ay' => ['name' => 'Aymara', 'script' => 'Latn', 'native' => 'aymar aru', 'regional' => 'ay_PE'],
        'az' => ['name' => 'Azerbaijani (Latin)', 'script' => 'Latn', 'native' => 'azərbaycanca', 'regional' => 'az_AZ'],
        'id' => ['name' => 'Indonesian', 'script' => 'Latn', 'native' => 'Bahasa Indonesia', 'regional' => 'id_ID'],
        'ms' => ['name' => 'Malay', 'script' => 'Latn', 'native' => 'Bahasa Melayu', 'regional' => 'ms_MY'],
        'bm' => ['name' => 'Bambara', 'script' => 'Latn', 'native' => 'bamanakan', 'regional' => ''],
        'jv' => ['name' => 'Javanese (Latin)', 'script' => 'Latn', 'native' => 'Basa Jawa', 'regional' => ''],
        'su' => ['name' => 'Sundanese', 'script' => 'Latn', 'native' => 'Basa Sunda', 'regional' => ''],
        'bh' => ['name' => 'Bihari', 'script' => 'Latn', 'native' => 'Bihari', 'regional' => ''],
        'bi' => ['name' => 'Bislama', 'script' => 'Latn', 'native' => 'Bislama', 'regional' => ''],
        'nb' => ['name' => 'Norwegian Bokmål', 'script' => 'Latn', 'native' => 'Bokmål', 'regional' => 'nb_NO'],
        'bs' => ['name' => 'Bosnian', 'script' => 'Latn', 'native' => 'bosanski', 'regional' => 'bs_BA'],
        'br' => ['name' => 'Breton', 'script' => 'Latn', 'native' => 'brezhoneg', 'regional' => 'br_FR'],
        'ca' => ['name' => 'Catalan', 'script' => 'Latn', 'native' => 'català', 'regional' => 'ca_ES'],
        'ch' => ['name' => 'Chamorro', 'script' => 'Latn', 'native' => 'Chamoru', 'regional' => ''],
        'ny' => ['name' => 'Chewa', 'script' => 'Latn', 'native' => 'chiCheŵa', 'regional' => ''],
        'kde' => ['name' => 'Makonde', 'script' => 'Latn', 'native' => 'Chimakonde', 'regional' => ''],
        'sn' => ['name' => 'Shona', 'script' => 'Latn', 'native' => 'chiShona', 'regional' => ''],
        'co' => ['name' => 'Corsican', 'script' => 'Latn', 'native' => 'corsu', 'regional' => ''],
        'cy' => ['name' => 'Welsh', 'script' => 'Latn', 'native' => 'Cymraeg', 'regional' => 'cy_GB'],
        'da' => ['name' => 'Danish', 'script' => 'Latn', 'native' => 'dansk', 'regional' => 'da_DK'],
        'se' => ['name' => 'Northern Sami', 'script' => 'Latn', 'native' => 'davvisámegiella', 'regional' => 'se_NO'],
        'de' => ['name' => 'German', 'script' => 'Latn', 'native' => 'Deutsch', 'regional' => 'de_DE'],
        'luo' => ['name' => 'Luo', 'script' => 'Latn', 'native' => 'Dholuo', 'regional' => ''],
        'nv' => ['name' => 'Navajo', 'script' => 'Latn', 'native' => 'Diné bizaad', 'regional' => ''],
        'dua' => ['name' => 'Duala', 'script' => 'Latn', 'native' => 'duálá', 'regional' => ''],
        'et' => ['name' => 'Estonian', 'script' => 'Latn', 'native' => 'eesti', 'regional' => 'et_EE'],
        'na' => ['name' => 'Nauru', 'script' => 'Latn', 'native' => 'Ekakairũ Naoero', 'regional' => ''],
        'guz' => ['name' => 'Ekegusii', 'script' => 'Latn', 'native' => 'Ekegusii', 'regional' => ''],
        'en' => ['name' => 'English', 'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
        'en-AU' => ['name' => 'Australian English', 'script' => 'Latn', 'native' => 'Australian English', 'regional' => 'en_AU'],
        'en-GB' => ['name' => 'British English', 'script' => 'Latn', 'native' => 'British English', 'regional' => 'en_GB'],
        'en-US' => ['name' => 'U.S. English', 'script' => 'Latn', 'native' => 'U.S. English', 'regional' => 'en_US'],
        'es' => ['name' => 'Spanish', 'script' => 'Latn', 'native' => 'español', 'regional' => 'es_ES'],
        'eo' => ['name' => 'Esperanto', 'script' => 'Latn', 'native' => 'esperanto', 'regional' => ''],
        'eu' => ['name' => 'Basque', 'script' => 'Latn', 'native' => 'euskara', 'regional' => 'eu_ES'],
        'ewo' => ['name' => 'Ewondo', 'script' => 'Latn', 'native' => 'ewondo', 'regional' => ''],
        'ee' => ['name' => 'Ewe', 'script' => 'Latn', 'native' => 'eʋegbe', 'regional' => ''],
        'fil' => ['name' => 'Filipino', 'script' => 'Latn', 'native' => 'Filipino', 'regional' => 'fil_PH'],
        'fr' => ['name' => 'French', 'script' => 'Latn', 'native' => 'français', 'regional' => 'fr_FR'],
        'fr-CA' => ['name' => 'Canadian French', 'script' => 'Latn', 'native' => 'français canadien', 'regional' => 'fr_CA'],
        'fy' => ['name' => 'Western Frisian', 'script' => 'Latn', 'native' => 'frysk', 'regional' => 'fy_DE'],
        'fur' => ['name' => 'Friulian', 'script' => 'Latn', 'native' => 'furlan', 'regional' => 'fur_IT'],
        'fo' => ['name' => 'Faroese', 'script' => 'Latn', 'native' => 'føroyskt', 'regional' => 'fo_FO'],
        'gaa' => ['name' => 'Ga', 'script' => 'Latn', 'native' => 'Ga', 'regional' => ''],
        'ga' => ['name' => 'Irish', 'script' => 'Latn', 'native' => 'Gaeilge', 'regional' => 'ga_IE'],
        'gv' => ['name' => 'Manx', 'script' => 'Latn', 'native' => 'Gaelg', 'regional' => 'gv_GB'],
        'sm' => ['name' => 'Samoan', 'script' => 'Latn', 'native' => 'Gagana fa’a Sāmoa', 'regional' => ''],
        'gl' => ['name' => 'Galician', 'script' => 'Latn', 'native' => 'galego', 'regional' => 'gl_ES'],
        'ki' => ['name' => 'Kikuyu', 'script' => 'Latn', 'native' => 'Gikuyu', 'regional' => ''],
        'gd' => ['name' => 'Scottish Gaelic', 'script' => 'Latn', 'native' => 'Gàidhlig', 'regional' => 'gd_GB'],
        'ha' => ['name' => 'Hausa', 'script' => 'Latn', 'native' => 'Hausa', 'regional' => 'ha_NG'],
        'bez' => ['name' => 'Bena', 'script' => 'Latn', 'native' => 'Hibena', 'regional' => ''],
        'ho' => ['name' => 'Hiri Motu', 'script' => 'Latn', 'native' => 'Hiri Motu', 'regional' => ''],
        'hr' => ['name' => 'Croatian', 'script' => 'Latn', 'native' => 'hrvatski', 'regional' => 'hr_HR'],
        'bem' => ['name' => 'Bemba', 'script' => 'Latn', 'native' => 'Ichibemba', 'regional' => 'bem_ZM'],
        'io' => ['name' => 'Ido', 'script' => 'Latn', 'native' => 'Ido', 'regional' => ''],
        'ig' => ['name' => 'Igbo', 'script' => 'Latn', 'native' => 'Igbo', 'regional' => 'ig_NG'],
        'rn' => ['name' => 'Rundi', 'script' => 'Latn', 'native' => 'Ikirundi', 'regional' => ''],
        'ia' => ['name' => 'Interlingua', 'script' => 'Latn', 'native' => 'interlingua', 'regional' => 'ia_FR'],
        'iu-Latn' => ['name' => 'Inuktitut (Latin)', 'script' => 'Latn', 'native' => 'Inuktitut', 'regional' => 'iu_CA'],
        'sbp' => ['name' => 'Sileibi', 'script' => 'Latn', 'native' => 'Ishisangu', 'regional' => ''],
        'nd' => ['name' => 'North Ndebele', 'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => ''],
        'nr' => ['name' => 'South Ndebele', 'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => 'nr_ZA'],
        'xh' => ['name' => 'Xhosa', 'script' => 'Latn', 'native' => 'isiXhosa', 'regional' => 'xh_ZA'],
        'zu' => ['name' => 'Zulu', 'script' => 'Latn', 'native' => 'isiZulu', 'regional' => 'zu_ZA'],
        'it' => ['name' => 'Italian', 'script' => 'Latn', 'native' => 'italiano', 'regional' => 'it_IT'],
        'ik' => ['name' => 'Inupiaq', 'script' => 'Latn', 'native' => 'Iñupiaq', 'regional' => 'ik_CA'],
        'dyo' => ['name' => 'Jola-Fonyi', 'script' => 'Latn', 'native' => 'joola', 'regional' => ''],
        'kea' => ['name' => 'Kabuverdianu', 'script' => 'Latn', 'native' => 'kabuverdianu', 'regional' => ''],
        'kaj' => ['name' => 'Jju', 'script' => 'Latn', 'native' => 'Kaje', 'regional' => ''],
        'mh' => ['name' => 'Marshallese', 'script' => 'Latn', 'native' => 'Kajin M̧ajeļ', 'regional' => 'mh_MH'],
        'kl' => ['name' => 'Kalaallisut', 'script' => 'Latn', 'native' => 'kalaallisut', 'regional' => 'kl_GL'],
        'kln' => ['name' => 'Kalenjin', 'script' => 'Latn', 'native' => 'Kalenjin', 'regional' => ''],
        'kr' => ['name' => 'Kanuri', 'script' => 'Latn', 'native' => 'Kanuri', 'regional' => ''],
        'kcg' => ['name' => 'Tyap', 'script' => 'Latn', 'native' => 'Katab', 'regional' => ''],
        'kw' => ['name' => 'Cornish', 'script' => 'Latn', 'native' => 'kernewek', 'regional' => 'kw_GB'],
        'naq' => ['name' => 'Nama', 'script' => 'Latn', 'native' => 'Khoekhoegowab', 'regional' => ''],
        'rof' => ['name' => 'Rombo', 'script' => 'Latn', 'native' => 'Kihorombo', 'regional' => ''],
        'kam' => ['name' => 'Kamba', 'script' => 'Latn', 'native' => 'Kikamba', 'regional' => ''],
        'kg' => ['name' => 'Kongo', 'script' => 'Latn', 'native' => 'Kikongo', 'regional' => ''],
        'jmc' => ['name' => 'Machame', 'script' => 'Latn', 'native' => 'Kimachame', 'regional' => ''],
        'rw' => ['name' => 'Kinyarwanda', 'script' => 'Latn', 'native' => 'Kinyarwanda', 'regional' => 'rw_RW'],
        'asa' => ['name' => 'Kipare', 'script' => 'Latn', 'native' => 'Kipare', 'regional' => ''],
        'rwk' => ['name' => 'Rwa', 'script' => 'Latn', 'native' => 'Kiruwa', 'regional' => ''],
        'saq' => ['name' => 'Samburu', 'script' => 'Latn', 'native' => 'Kisampur', 'regional' => ''],
        'ksb' => ['name' => 'Shambala', 'script' => 'Latn', 'native' => 'Kishambaa', 'regional' => ''],
        'swc' => ['name' => 'Congo Swahili', 'script' => 'Latn', 'native' => 'Kiswahili ya Kongo', 'regional' => ''],
        'sw' => ['name' => 'Swahili', 'script' => 'Latn', 'native' => 'Kiswahili', 'regional' => 'sw_KE'],
        'dav' => ['name' => 'Dawida', 'script' => 'Latn', 'native' => 'Kitaita', 'regional' => ''],
        'teo' => ['name' => 'Teso', 'script' => 'Latn', 'native' => 'Kiteso', 'regional' => ''],
        'khq' => ['name' => 'Koyra Chiini', 'script' => 'Latn', 'native' => 'Koyra ciini', 'regional' => ''],
        'ses' => ['name' => 'Songhay', 'script' => 'Latn', 'native' => 'Koyraboro senni', 'regional' => ''],
        'mfe' => ['name' => 'Morisyen', 'script' => 'Latn', 'native' => 'kreol morisien', 'regional' => ''],
        'ht' => ['name' => 'Haitian', 'script' => 'Latn', 'native' => 'Kreyòl ayisyen', 'regional' => 'ht_HT'],
        'kj' => ['name' => 'Kuanyama', 'script' => 'Latn', 'native' => 'Kwanyama', 'regional' => ''],
        'ksh' => ['name' => 'Kölsch', 'script' => 'Latn', 'native' => 'Kölsch', 'regional' => ''],
        'ebu' => ['name' => 'Kiembu', 'script' => 'Latn', 'native' => 'Kĩembu', 'regional' => ''],
        'mer' => ['name' => 'Kimîîru', 'script' => 'Latn', 'native' => 'Kĩmĩrũ', 'regional' => ''],
        'lag' => ['name' => 'Langi', 'script' => 'Latn', 'native' => 'Kɨlaangi', 'regional' => ''],
        'lah' => ['name' => 'Lahnda', 'script' => 'Latn', 'native' => 'Lahnda', 'regional' => ''],
        'la' => ['name' => 'Latin', 'script' => 'Latn', 'native' => 'latine', 'regional' => ''],
        'lv' => ['name' => 'Latvian', 'script' => 'Latn', 'native' => 'latviešu', 'regional' => 'lv_LV'],
        'to' => ['name' => 'Tongan', 'script' => 'Latn', 'native' => 'lea fakatonga', 'regional' => ''],
        'lt' => ['name' => 'Lithuanian', 'script' => 'Latn', 'native' => 'lietuvių', 'regional' => 'lt_LT'],
        'li' => ['name' => 'Limburgish', 'script' => 'Latn', 'native' => 'Limburgs', 'regional' => 'li_BE'],
        'ln' => ['name' => 'Lingala', 'script' => 'Latn', 'native' => 'lingála', 'regional' => ''],
        'lg' => ['name' => 'Ganda', 'script' => 'Latn', 'native' => 'Luganda', 'regional' => 'lg_UG'],
        'luy' => ['name' => 'Oluluyia', 'script' => 'Latn', 'native' => 'Luluhia', 'regional' => ''],
        'lb' => ['name' => 'Luxembourgish', 'script' => 'Latn', 'native' => 'Lëtzebuergesch', 'regional' => 'lb_LU'],
        'hu' => ['name' => 'Hungarian', 'script' => 'Latn', 'native' => 'magyar', 'regional' => 'hu_HU'],
        'mgh' => ['name' => 'Makhuwa-Meetto', 'script' => 'Latn', 'native' => 'Makua', 'regional' => ''],
        'mg' => ['name' => 'Malagasy', 'script' => 'Latn', 'native' => 'Malagasy', 'regional' => 'mg_MG'],
        'mt' => ['name' => 'Maltese', 'script' => 'Latn', 'native' => 'Malti', 'regional' => 'mt_MT'],
        'mtr' => ['name' => 'Mewari', 'script' => 'Latn', 'native' => 'Mewari', 'regional' => ''],
        'mua' => ['name' => 'Mundang', 'script' => 'Latn', 'native' => 'Mundang', 'regional' => ''],
        'mi' => ['name' => 'Māori', 'script' => 'Latn', 'native' => 'Māori', 'regional' => 'mi_NZ'],
        'nl' => ['name' => 'Dutch', 'script' => 'Latn', 'native' => 'Nederlands', 'regional' => 'nl_NL'],
        'nmg' => ['name' => 'Kwasio', 'script' => 'Latn', 'native' => 'ngumba', 'regional' => ''],
        'yav' => ['name' => 'Yangben', 'script' => 'Latn', 'native' => 'nuasue', 'regional' => ''],
        'nn' => ['name' => 'Norwegian Nynorsk', 'script' => 'Latn', 'native' => 'nynorsk', 'regional' => 'nn_NO'],
        'oc' => ['name' => 'Occitan', 'script' => 'Latn', 'native' => 'occitan', 'regional' => 'oc_FR'],
        'ang' => ['name' => 'Old English', 'script' => 'Runr', 'native' => 'Old English', 'regional' => ''],
        'xog' => ['name' => 'Soga', 'script' => 'Latn', 'native' => 'Olusoga', 'regional' => ''],
        'om' => ['name' => 'Oromo', 'script' => 'Latn', 'native' => 'Oromoo', 'regional' => 'om_ET'],
        'ng' => ['name' => 'Ndonga', 'script' => 'Latn', 'native' => 'OshiNdonga', 'regional' => ''],
        'hz' => ['name' => 'Herero', 'script' => 'Latn', 'native' => 'Otjiherero', 'regional' => ''],
        'uz-Latn' => ['name' => 'Uzbek (Latin)', 'script' => 'Latn', 'native' => 'oʼzbekcha', 'regional' => 'uz_UZ'],
        'nds' => ['name' => 'Low German', 'script' => 'Latn', 'native' => 'Plattdüütsch', 'regional' => 'nds_DE'],
        'pl' => ['name' => 'Polish', 'script' => 'Latn', 'native' => 'polski', 'regional' => 'pl_PL'],
        'pt' => ['name' => 'Portuguese', 'script' => 'Latn', 'native' => 'português', 'regional' => 'pt_PT'],
        'pt-BR' => ['name' => 'Brazilian Portuguese', 'script' => 'Latn', 'native' => 'português do Brasil', 'regional' => 'pt_BR'],
        'ff' => ['name' => 'Fulah', 'script' => 'Latn', 'native' => 'Pulaar', 'regional' => 'ff_SN'],
        'pi' => ['name' => 'Pahari-Potwari', 'script' => 'Latn', 'native' => 'Pāli', 'regional' => ''],
        'aa' => ['name' => 'Afar', 'script' => 'Latn', 'native' => 'Qafar', 'regional' => 'aa_ER'],
        'ty' => ['name' => 'Tahitian', 'script' => 'Latn', 'native' => 'Reo Māohi', 'regional' => ''],
        'ksf' => ['name' => 'Bafia', 'script' => 'Latn', 'native' => 'rikpa', 'regional' => ''],
        'ro' => ['name' => 'Romanian', 'script' => 'Latn', 'native' => 'română', 'regional' => 'ro_RO'],
        'cgg' => ['name' => 'Chiga', 'script' => 'Latn', 'native' => 'Rukiga', 'regional' => ''],
        'rm' => ['name' => 'Romansh', 'script' => 'Latn', 'native' => 'rumantsch', 'regional' => ''],
        'qu' => ['name' => 'Quechua', 'script' => 'Latn', 'native' => 'Runa Simi', 'regional' => ''],
        'nyn' => ['name' => 'Nyankole', 'script' => 'Latn', 'native' => 'Runyankore', 'regional' => ''],
        'ssy' => ['name' => 'Saho', 'script' => 'Latn', 'native' => 'Saho', 'regional' => ''],
        'sc' => ['name' => 'Sardinian', 'script' => 'Latn', 'native' => 'sardu', 'regional' => 'sc_IT'],
        'de-CH' => ['name' => 'Swiss High German', 'script' => 'Latn', 'native' => 'Schweizer Hochdeutsch', 'regional' => 'de_CH'],
        'gsw' => ['name' => 'Swiss German', 'script' => 'Latn', 'native' => 'Schwiizertüütsch', 'regional' => ''],
        'trv' => ['name' => 'Taroko', 'script' => 'Latn', 'native' => 'Seediq', 'regional' => ''],
        'seh' => ['name' => 'Sena', 'script' => 'Latn', 'native' => 'sena', 'regional' => ''],
        'nso' => ['name' => 'Northern Sotho', 'script' => 'Latn', 'native' => 'Sesotho sa Leboa', 'regional' => 'nso_ZA'],
        'st' => ['name' => 'Southern Sotho', 'script' => 'Latn', 'native' => 'Sesotho', 'regional' => 'st_ZA'],
        'tn' => ['name' => 'Tswana', 'script' => 'Latn', 'native' => 'Setswana', 'regional' => 'tn_ZA'],
        'sq' => ['name' => 'Albanian', 'script' => 'Latn', 'native' => 'shqip', 'regional' => 'sq_AL'],
        'sid' => ['name' => 'Sidamo', 'script' => 'Latn', 'native' => 'Sidaamu Afo', 'regional' => 'sid_ET'],
        'ss' => ['name' => 'Swati', 'script' => 'Latn', 'native' => 'Siswati', 'regional' => 'ss_ZA'],
        'sk' => ['name' => 'Slovak', 'script' => 'Latn', 'native' => 'slovenčina', 'regional' => 'sk_SK'],
        'sl' => ['name' => 'Slovene', 'script' => 'Latn', 'native' => 'slovenščina', 'regional' => 'sl_SI'],
        'so' => ['name' => 'Somali', 'script' => 'Latn', 'native' => 'Soomaali', 'regional' => 'so_SO'],
        'sr-Latn' => ['name' => 'Serbian (Latin)', 'script' => 'Latn', 'native' => 'Srpski', 'regional' => 'sr_RS'],
        'sh' => ['name' => 'Serbo-Croatian', 'script' => 'Latn', 'native' => 'srpskohrvatski', 'regional' => ''],
        'fi' => ['name' => 'Finnish', 'script' => 'Latn', 'native' => 'suomi', 'regional' => 'fi_FI'],
        'sv' => ['name' => 'Swedish', 'script' => 'Latn', 'native' => 'svenska', 'regional' => 'sv_SE'],
        'sg' => ['name' => 'Sango', 'script' => 'Latn', 'native' => 'Sängö', 'regional' => ''],
        'tl' => ['name' => 'Tagalog', 'script' => 'Latn', 'native' => 'Tagalog', 'regional' => 'tl_PH'],
        'tzm-Latn' => ['name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'native' => 'Tamazight', 'regional' => ''],
        'kab' => ['name' => 'Kabyle', 'script' => 'Latn', 'native' => 'Taqbaylit', 'regional' => 'kab_DZ'],
        'twq' => ['name' => 'Tasawaq', 'script' => 'Latn', 'native' => 'Tasawaq senni', 'regional' => ''],
        'shi' => ['name' => 'Tachelhit (Latin)', 'script' => 'Latn', 'native' => 'Tashelhit', 'regional' => ''],
        'nus' => ['name' => 'Nuer', 'script' => 'Latn', 'native' => 'Thok Nath', 'regional' => ''],
        'vi' => ['name' => 'Vietnamese', 'script' => 'Latn', 'native' => 'Tiếng Việt', 'regional' => 'vi_VN'],
        'tg-Latn' => ['name' => 'Tajik (Latin)', 'script' => 'Latn', 'native' => 'tojikī', 'regional' => 'tg_TJ'],
        'lu' => ['name' => 'Luba-Katanga', 'script' => 'Latn', 'native' => 'Tshiluba', 'regional' => 've_ZA'],
        've' => ['name' => 'Venda', 'script' => 'Latn', 'native' => 'Tshivenḓa', 'regional' => ''],
        'tw' => ['name' => 'Twi', 'script' => 'Latn', 'native' => 'Twi', 'regional' => ''],
        'tr' => ['name' => 'Turkish', 'script' => 'Latn', 'native' => 'Türkçe', 'regional' => 'tr_TR'],
        'ale' => ['name' => 'Aleut', 'script' => 'Latn', 'native' => 'Unangax tunuu', 'regional' => ''],
        'ca-valencia' => ['name' => 'Valencian', 'script' => 'Latn', 'native' => 'valencià', 'regional' => ''],
        'vai-Latn' => ['name' => 'Vai (Latin)', 'script' => 'Latn', 'native' => 'Viyamíĩ', 'regional' => ''],
        'vo' => ['name' => 'Volapük', 'script' => 'Latn', 'native' => 'Volapük', 'regional' => ''],
        'fj' => ['name' => 'Fijian', 'script' => 'Latn', 'native' => 'vosa Vakaviti', 'regional' => ''],
        'wa' => ['name' => 'Walloon', 'script' => 'Latn', 'native' => 'Walon', 'regional' => 'wa_BE'],
        'wae' => ['name' => 'Walser', 'script' => 'Latn', 'native' => 'Walser', 'regional' => 'wae_CH'],
        'wen' => ['name' => 'Sorbian', 'script' => 'Latn', 'native' => 'Wendic', 'regional' => ''],
        'wo' => ['name' => 'Wolof', 'script' => 'Latn', 'native' => 'Wolof', 'regional' => 'wo_SN'],
        'ts' => ['name' => 'Tsonga', 'script' => 'Latn', 'native' => 'Xitsonga', 'regional' => 'ts_ZA'],
        'dje' => ['name' => 'Zarma', 'script' => 'Latn', 'native' => 'Zarmaciine', 'regional' => ''],
        'yo' => ['name' => 'Yoruba', 'script' => 'Latn', 'native' => 'Èdè Yorùbá', 'regional' => 'yo_NG'],
        'de-AT' => ['name' => 'Austrian German', 'script' => 'Latn', 'native' => 'Österreichisches Deutsch', 'regional' => 'de_AT'],
        'is' => ['name' => 'Icelandic', 'script' => 'Latn', 'native' => 'íslenska', 'regional' => 'is_IS'],
        'cs' => ['name' => 'Czech', 'script' => 'Latn', 'native' => 'čeština', 'regional' => 'cs_CZ'],
        'bas' => ['name' => 'Basa', 'script' => 'Latn', 'native' => 'Ɓàsàa', 'regional' => ''],
        'mas' => ['name' => 'Masai', 'script' => 'Latn', 'native' => 'ɔl-Maa', 'regional' => ''],
        'haw' => ['name' => 'Hawaiian', 'script' => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi', 'regional' => ''],
        'el' => ['name' => 'Greek', 'script' => 'Grek', 'native' => 'Ελληνικά', 'regional' => 'el_GR'],
        'uz' => ['name' => 'Uzbek (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Ўзбек', 'regional' => 'uz_UZ'],
        'az-Cyrl' => ['name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Азәрбајҹан', 'regional' => 'uz_UZ'],
        'ab' => ['name' => 'Abkhazian', 'script' => 'Cyrl', 'native' => 'Аҧсуа', 'regional' => ''],
        'os' => ['name' => 'Ossetic', 'script' => 'Cyrl', 'native' => 'Ирон', 'regional' => 'os_RU'],
        'ky' => ['name' => 'Kyrgyz', 'script' => 'Cyrl', 'native' => 'Кыргыз', 'regional' => 'ky_KG'],
        'sr' => ['name' => 'Serbian (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Српски', 'regional' => 'sr_RS'],
        'av' => ['name' => 'Avaric', 'script' => 'Cyrl', 'native' => 'авар мацӀ', 'regional' => ''],
        'ady' => ['name' => 'Adyghe', 'script' => 'Cyrl', 'native' => 'адыгэбзэ', 'regional' => ''],
        'ba' => ['name' => 'Bashkir', 'script' => 'Cyrl', 'native' => 'башҡорт теле', 'regional' => ''],
        'be' => ['name' => 'Belarusian', 'script' => 'Cyrl', 'native' => 'беларуская', 'regional' => 'be_BY'],
        'bg' => ['name' => 'Bulgarian', 'script' => 'Cyrl', 'native' => 'български', 'regional' => 'bg_BG'],
        'kv' => ['name' => 'Komi', 'script' => 'Cyrl', 'native' => 'коми кыв', 'regional' => ''],
        'mk' => ['name' => 'Macedonian', 'script' => 'Cyrl', 'native' => 'македонски', 'regional' => 'mk_MK'],
        'mn' => ['name' => 'Mongolian (Cyrillic)', 'script' => 'Cyrl', 'native' => 'монгол', 'regional' => 'mn_MN'],
        'ce' => ['name' => 'Chechen', 'script' => 'Cyrl', 'native' => 'нохчийн мотт', 'regional' => 'ce_RU'],
        'ru' => ['name' => 'Russian', 'script' => 'Cyrl', 'native' => 'русский', 'regional' => 'ru_RU'],
        'sah' => ['name' => 'Yakut', 'script' => 'Cyrl', 'native' => 'саха тыла', 'regional' => ''],
        'tt' => ['name' => 'Tatar', 'script' => 'Cyrl', 'native' => 'татар теле', 'regional' => 'tt_RU'],
        'tg' => ['name' => 'Tajik (Cyrillic)', 'script' => 'Cyrl', 'native' => 'тоҷикӣ', 'regional' => 'tg_TJ'],
        'tk' => ['name' => 'Turkmen', 'script' => 'Cyrl', 'native' => 'түркменче', 'regional' => 'tk_TM'],
        'uk' => ['name' => 'Ukrainian', 'script' => 'Cyrl', 'native' => 'українська', 'regional' => 'uk_UA'],
        'cv' => ['name' => 'Chuvash', 'script' => 'Cyrl', 'native' => 'чӑваш чӗлхи', 'regional' => 'cv_RU'],
        'cu' => ['name' => 'Church Slavic', 'script' => 'Cyrl', 'native' => 'ѩзыкъ словѣньскъ', 'regional' => ''],
        'kk' => ['name' => 'Kazakh', 'script' => 'Cyrl', 'native' => 'қазақ тілі', 'regional' => 'kk_KZ'],
        'hy' => ['name' => 'Armenian', 'script' => 'Armn', 'native' => 'Հայերեն', 'regional' => 'hy_AM'],
        'yi' => ['name' => 'Yiddish', 'script' => 'Hebr', 'native' => 'ייִדיש', 'regional' => 'yi_US'],
        'he' => ['name' => 'Hebrew', 'script' => 'Hebr', 'native' => 'עברית', 'regional' => 'he_IL'],
        'ug' => ['name' => 'Uyghur', 'script' => 'Arab', 'native' => 'ئۇيغۇرچە', 'regional' => 'ug_CN'],
        'ur' => ['name' => 'Urdu', 'script' => 'Arab', 'native' => 'اردو', 'regional' => 'ur_PK'],
        'ar' => ['name' => 'Arabic', 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE'],
        'uz-Arab' => ['name' => 'Uzbek (Arabic)', 'script' => 'Arab', 'native' => 'اۉزبېک', 'regional' => ''],
        'tg-Arab' => ['name' => 'Tajik (Arabic)', 'script' => 'Arab', 'native' => 'تاجیکی', 'regional' => 'tg_TJ'],
        'sd' => ['name' => 'Sindhi', 'script' => 'Arab', 'native' => 'سنڌي', 'regional' => 'sd_IN'],
        'fa' => ['name' => 'Persian', 'script' => 'Arab', 'native' => 'فارسی', 'regional' => 'fa_IR'],
        'pa-Arab' => ['name' => 'Punjabi (Arabic)', 'script' => 'Arab', 'native' => 'پنجاب', 'regional' => 'pa_IN'],
        'ps' => ['name' => 'Pashto', 'script' => 'Arab', 'native' => 'پښتو', 'regional' => 'ps_AF'],
        'ks' => ['name' => 'Kashmiri (Arabic)', 'script' => 'Arab', 'native' => 'کأشُر', 'regional' => 'ks_IN'],
        'ku' => ['name' => 'Kurdish', 'script' => 'Arab', 'native' => 'کوردی', 'regional' => 'ku_TR'],
        'dv' => ['name' => 'Divehi', 'script' => 'Thaa', 'native' => 'ދިވެހިބަސް', 'regional' => 'dv_MV'],
        'ks-Deva' => ['name' => 'Kashmiri (Devaganari)', 'script' => 'Deva', 'native' => 'कॉशुर', 'regional' => 'ks_IN'],
        'kok' => ['name' => 'Konkani', 'script' => 'Deva', 'native' => 'कोंकणी', 'regional' => 'kok_IN'],
        'doi' => ['name' => 'Dogri', 'script' => 'Deva', 'native' => 'डोगरी', 'regional' => 'doi_IN'],
        'ne' => ['name' => 'Nepali', 'script' => 'Deva', 'native' => 'नेपाली', 'regional' => ''],
        'pra' => ['name' => 'Prakrit', 'script' => 'Deva', 'native' => 'प्राकृत', 'regional' => ''],
        'brx' => ['name' => 'Bodo', 'script' => 'Deva', 'native' => 'बड़ो', 'regional' => 'brx_IN'],
        'bra' => ['name' => 'Braj', 'script' => 'Deva', 'native' => 'ब्रज भाषा', 'regional' => ''],
        'mr' => ['name' => 'Marathi', 'script' => 'Deva', 'native' => 'मराठी', 'regional' => 'mr_IN'],
        'mai' => ['name' => 'Maithili', 'script' => 'Tirh', 'native' => 'मैथिली', 'regional' => 'mai_IN'],
        'raj' => ['name' => 'Rajasthani', 'script' => 'Deva', 'native' => 'राजस्थानी', 'regional' => ''],
        'sa' => ['name' => 'Sanskrit', 'script' => 'Deva', 'native' => 'संस्कृतम्', 'regional' => 'sa_IN'],
        'hi' => ['name' => 'Hindi', 'script' => 'Deva', 'native' => 'हिन्दी', 'regional' => 'hi_IN'],
        'as' => ['name' => 'Assamese', 'script' => 'Beng', 'native' => 'অসমীয়া', 'regional' => 'as_IN'],
        'bn' => ['name' => 'Bengali', 'script' => 'Beng', 'native' => 'বাংলা', 'regional' => 'bn_BD'],
        'mni' => ['name' => 'Manipuri', 'script' => 'Beng', 'native' => 'মৈতৈ', 'regional' => 'mni_IN'],
        'pa' => ['name' => 'Punjabi (Gurmukhi)', 'script' => 'Guru', 'native' => 'ਪੰਜਾਬੀ', 'regional' => 'pa_IN'],
        'gu' => ['name' => 'Gujarati', 'script' => 'Gujr', 'native' => 'ગુજરાતી', 'regional' => 'gu_IN'],
        'or' => ['name' => 'Oriya', 'script' => 'Orya', 'native' => 'ଓଡ଼ିଆ', 'regional' => 'or_IN'],
        'ta' => ['name' => 'Tamil', 'script' => 'Taml', 'native' => 'தமிழ்', 'regional' => 'ta_IN'],
        'te' => ['name' => 'Telugu', 'script' => 'Telu', 'native' => 'తెలుగు', 'regional' => 'te_IN'],
        'kn' => ['name' => 'Kannada', 'script' => 'Knda', 'native' => 'ಕನ್ನಡ', 'regional' => 'kn_IN'],
        'ml' => ['name' => 'Malayalam', 'script' => 'Mlym', 'native' => 'മലയാളം', 'regional' => 'ml_IN'],
        'si' => ['name' => 'Sinhala', 'script' => 'Sinh', 'native' => 'සිංහල', 'regional' => 'si_LK'],
        'th' => ['name' => 'Thai', 'script' => 'Thai', 'native' => 'ไทย', 'regional' => 'th_TH'],
        'lo' => ['name' => 'Lao', 'script' => 'Laoo', 'native' => 'ລາວ', 'regional' => 'lo_LA'],
        'bo' => ['name' => 'Tibetan', 'script' => 'Tibt', 'native' => 'པོད་སྐད་', 'regional' => 'bo_IN'],
        'dz' => ['name' => 'Dzongkha', 'script' => 'Tibt', 'native' => 'རྫོང་ཁ', 'regional' => 'dz_BT'],
        'my' => ['name' => 'Burmese', 'script' => 'Mymr', 'native' => 'မြန်မာဘာသာ', 'regional' => 'my_MM'],
        'ka' => ['name' => 'Georgian', 'script' => 'Geor', 'native' => 'ქართული', 'regional' => 'ka_GE'],
        'byn' => ['name' => 'Blin', 'script' => 'Ethi', 'native' => 'ብሊን', 'regional' => 'byn_ER'],
        'tig' => ['name' => 'Tigre', 'script' => 'Ethi', 'native' => 'ትግረ', 'regional' => 'tig_ER'],
        'ti' => ['name' => 'Tigrinya', 'script' => 'Ethi', 'native' => 'ትግርኛ', 'regional' => 'ti_ET'],
        'am' => ['name' => 'Amharic', 'script' => 'Ethi', 'native' => 'አማርኛ', 'regional' => 'am_ET'],
        'wal' => ['name' => 'Wolaytta', 'script' => 'Ethi', 'native' => 'ወላይታቱ', 'regional' => 'wal_ET'],
        'chr' => ['name' => 'Cherokee', 'script' => 'Cher', 'native' => 'ᏣᎳᎩ', 'regional' => ''],
        'iu' => ['name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'regional' => 'iu_CA'],
        'oj' => ['name' => 'Ojibwa', 'script' => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'regional' => ''],
        'cr' => ['name' => 'Cree', 'script' => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'regional' => ''],
        'km' => ['name' => 'Khmer', 'script' => 'Khmr', 'native' => 'ភាសាខ្មែរ', 'regional' => 'km_KH'],
        'mn-Mong' => ['name' => 'Mongolian (Mongolian)', 'script' => 'Mong', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ', 'regional' => 'mn_MN'],
        'shi-Tfng' => ['name' => 'Tachelhit (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => ''],
        'tzm' => ['name' => 'Central Atlas Tamazight (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => ''],
        'yue' => ['name' => 'Yue', 'script' => 'Hant', 'native' => '廣州話', 'regional' => 'yue_HK'],
        'ja' => ['name' => 'Japanese', 'script' => 'Jpan', 'native' => '日本語', 'regional' => 'ja_JP'],
        'zh' => ['name' => 'Chinese (Simplified)', 'script' => 'Hans', 'native' => '简体中文', 'regional' => 'zh_CN'],
        'zh-Hant' => ['name' => 'Chinese (Traditional)', 'script' => 'Hant', 'native' => '繁體中文', 'regional' => 'zh_CN'],
        'ii' => ['name' => 'Sichuan Yi', 'script' => 'Yiii', 'native' => 'ꆈꌠꉙ', 'regional' => ''],
        'vai' => ['name' => 'Vai (Vai)', 'script' => 'Vaii', 'native' => 'ꕙꔤ', 'regional' => ''],
        'jv-Java' => ['name' => 'Javanese (Javanese)', 'script' => 'Java', 'native' => 'ꦧꦱꦗꦮ', 'regional' => ''],
        'ko' => ['name' => 'Korean', 'script' => 'Hang', 'native' => '한국어', 'regional' => 'ko_KR'],
    ],

    'countries' => [
        'AF' => ['name' => 'Afghanistan (‫افغانستان‬‎)', 'calling_code' => '93'],
        'AX' => ['name' => 'Åland Islands (Åland)', 'calling_code' => '358'],
        'AL' => ['name' => 'Albania (Shqipëri)', 'calling_code' => '355'],
        'DZ' => ['name' => 'Algeria (‫الجزائر‬‎)', 'calling_code' => '213'],
        'AS' => ['name' => 'American Samoa', 'calling_code' => '1'],
        'AD' => ['name' => 'Andorra', 'calling_code' => '376'],
        'AO' => ['name' => 'Angola', 'calling_code' => '244'],
        'AI' => ['name' => 'Anguilla', 'calling_code' => '1'],
        'AQ' => ['name' => 'Antarctica', 'calling_code' => ''],
        'AG' => ['name' => 'Antigua and Barbuda', 'calling_code' => '1'],
        'AR' => ['name' => 'Argentina', 'calling_code' => '54'],
        'AM' => ['name' => 'Armenia (Հայաստան)', 'calling_code' => '374'],
        'AW' => ['name' => 'Aruba', 'calling_code' => '297'],
        'AC' => ['name' => 'Ascension Island', 'calling_code' => '247'],
        'AU' => ['name' => 'Australia', 'calling_code' => '61'],
        'AT' => ['name' => 'Austria (Österreich)', 'calling_code' => '43'],
        'AZ' => ['name' => 'Azerbaijan (Azərbaycan)', 'calling_code' => '994'],
        'BS' => ['name' => 'Bahamas', 'calling_code' => '1'],
        'BH' => ['name' => 'Bahrain (‫البحرين‬‎)', 'calling_code' => '973'],
        'BD' => ['name' => 'Bangladesh (বাংলাদেশ)', 'calling_code' => '880'],
        'BB' => ['name' => 'Barbados', 'calling_code' => '1'],
        'BY' => ['name' => 'Belarus (Беларусь)', 'calling_code' => '375'],
        'BE' => ['name' => 'Belgium (België)', 'calling_code' => '32'],
        'BZ' => ['name' => 'Belize', 'calling_code' => '501'],
        'BJ' => ['name' => 'Benin (Bénin)', 'calling_code' => '229'],
        'BM' => ['name' => 'Bermuda', 'calling_code' => '1'],
        'BT' => ['name' => 'Bhutan (འབྲུག)', 'calling_code' => '975'],
        'BO' => ['name' => 'Bolivia', 'calling_code' => '591'],
        'BQ' => ['name' => 'Bonaire, Sint Eustatius and Saba', 'calling_code' => '599'],
        'BA' => ['name' => 'Bosnia and Herzegovina (Босна и Херцеговина)', 'calling_code' => '387'],
        'BW' => ['name' => 'Botswana', 'calling_code' => '267'],
        'BV' => ['name' => 'Bouvet Island', 'calling_code' => '47'],
        'BR' => ['name' => 'Brazil (Brasil)', 'calling_code' => '55'],
        'IO' => ['name' => 'British Indian Ocean Territory', 'calling_code' => '246'],
        'VG' => ['name' => 'British Virgin Islands', 'calling_code' => '1'],
        'BN' => ['name' => 'Brunei Darussalam', 'calling_code' => '673'],
        'BG' => ['name' => 'Bulgaria (България)', 'calling_code' => '359'],
        'BF' => ['name' => 'Burkina Faso', 'calling_code' => '226'],
        'BI' => ['name' => 'Burundi (Uburundi)', 'calling_code' => '257'],
        'KH' => ['name' => 'Cambodia (កម្ពុជា)', 'calling_code' => '855'],
        'CM' => ['name' => 'Cameroon (Cameroun)', 'calling_code' => '237'],
        'CA' => ['name' => 'Canada', 'calling_code' => '1'],
        'IC' => ['name' => 'Canary Islands (islas Canarias)', 'calling_code' => '34'],
        'CV' => ['name' => 'Cape Verde (Kabu Verdi)', 'calling_code' => '238'],
        'KY' => ['name' => 'Cayman Islands', 'calling_code' => '1'],
        'CF' => ['name' => 'Central African Republic (République centrafricaine)', 'calling_code' => '236'],
        'EA' => ['name' => 'Ceuta and Melilla (Ceuta y Melilla)', 'calling_code' => '34'],
        'TD' => ['name' => 'Chad (Tchad)', 'calling_code' => '235'],
        'CL' => ['name' => 'Chile', 'calling_code' => '56'],
        'CN' => ['name' => 'China (中国)', 'calling_code' => '86'],
        'CX' => ['name' => 'Christmas Island', 'calling_code' => '61'],
        'CP' => ['name' => 'Clipperton Island', 'calling_code' => ''],
        'CC' => ['name' => 'Cocos (Keeling) Islands (Kepulauan Cocos (Keeling))', 'calling_code' => '61'],
        'CO' => ['name' => 'Colombia', 'calling_code' => '57'],
        'KM' => ['name' => 'Comoros (‫جزر القمر‬‎)', 'calling_code' => '269'],
        'CD' => ['name' => 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)', 'calling_code' => '243'],
        'CG' => ['name' => 'Congo (Republic) (Congo-Brazzaville)', 'calling_code' => '242'],
        'CK' => ['name' => 'Cook Islands', 'calling_code' => '682'],
        'CR' => ['name' => 'Costa Rica', 'calling_code' => '506'],
        'CI' => ['name' => 'Côte d’Ivoire', 'calling_code' => '225'],
        'HR' => ['name' => 'Croatia (Hrvatska)', 'calling_code' => '385'],
        'CU' => ['name' => 'Cuba', 'calling_code' => '53'],
        'CW' => ['name' => 'Curaçao', 'calling_code' => '599'],
        'CY' => ['name' => 'Cyprus (Κύπρος)', 'calling_code' => '357'],
        'CZ' => ['name' => 'Czech Republic (Česká republika)', 'calling_code' => '420'],
        'DK' => ['name' => 'Denmark (Danmark)', 'calling_code' => '45'],
        'DG' => ['name' => 'Diego Garcia', 'calling_code' => '246'],
        'DJ' => ['name' => 'Djibouti', 'calling_code' => '253'],
        'DM' => ['name' => 'Dominica', 'calling_code' => '1'],
        'DO' => ['name' => 'Dominican Republic (República Dominicana)', 'calling_code' => '1'],
        'EC' => ['name' => 'Ecuador', 'calling_code' => '593'],
        'EG' => ['name' => 'Egypt (‫مصر‬‎)', 'calling_code' => '20'],
        'SV' => ['name' => 'El Salvador', 'calling_code' => '503'],
        'GQ' => ['name' => 'Equatorial Guinea (Guinea Ecuatorial)', 'calling_code' => '249'],
        'ER' => ['name' => 'Eritrea', 'calling_code' => '291'],
        'EE' => ['name' => 'Estonia (Eesti)', 'calling_code' => '372'],
        'ET' => ['name' => 'Ethiopia', 'calling_code' => '251'],
        'FK' => ['name' => 'Falkland Islands (Islas Malvinas)', 'calling_code' => '500'],
        'FO' => ['name' => 'Faroe Islands (Føroyar)', 'calling_code' => '298'],
        'FJ' => ['name' => 'Fiji', 'calling_code' => '679'],
        'FI' => ['name' => 'Finland (Suomi)', 'calling_code' => '358'],
        'FR' => ['name' => 'France', 'calling_code' => '33'],
        'GF' => ['name' => 'French Guiana (Guyane française)', 'calling_code' => '594'],
        'PF' => ['name' => 'French Polynesia (Polynésie française)', 'calling_code' => '689'],
        'TF' => ['name' => 'French Southern Territories (Terres australes françaises)', 'calling_code' => '262'],
        'GA' => ['name' => 'Gabon', 'calling_code' => '241'],
        'GM' => ['name' => 'Gambia', 'calling_code' => '220'],
        'GE' => ['name' => 'Georgia (საქართველო)', 'calling_code' => '995'],
        'DE' => ['name' => 'Germany (Deutschland)', 'calling_code' => '49'],
        'GH' => ['name' => 'Ghana (Gaana)', 'calling_code' => '233'],
        'GI' => ['name' => 'Gibraltar', 'calling_code' => '350'],
        'GR' => ['name' => 'Greece (Ελλάδα)', 'calling_code' => '30'],
        'GL' => ['name' => 'Greenland (Kalaallit Nunaat)', 'calling_code' => '299'],
        'GD' => ['name' => 'Grenada', 'calling_code' => '1'],
        'GP' => ['name' => 'Guadeloupe', 'calling_code' => '590'],
        'GU' => ['name' => 'Guam', 'calling_code' => '1'],
        'GT' => ['name' => 'Guatemala', 'calling_code' => '502'],
        'GG' => ['name' => 'Guernsey', 'calling_code' => '44'],
        'GN' => ['name' => 'Guinea (Guinée)', 'calling_code' => '224'],
        'GW' => ['name' => 'Guinea-Bissau (Guiné Bissau)', 'calling_code' => '245'],
        'GY' => ['name' => 'Guyana', 'calling_code' => '592'],
        'HT' => ['name' => 'Haiti', 'calling_code' => '509'],
        'HM' => ['name' => 'Heard Island and McDonald Islands', 'calling_code' => ''],
        'HN' => ['name' => 'Honduras', 'calling_code' => '504'],
        'HK' => ['name' => 'Hong Kong (香港)', 'calling_code' => '852'],
        'HU' => ['name' => 'Hungary (Magyarország)', 'calling_code' => '36'],
        'IS' => ['name' => 'Iceland (Ísland)', 'calling_code' => '354'],
        'IN' => ['name' => 'India (भारत)', 'calling_code' => '91'],
        'ID' => ['name' => 'Indonesia', 'calling_code' => '62'],
        'IR' => ['name' => 'Iran (‫ایران‬‎)', 'calling_code' => '98'],
        'IQ' => ['name' => 'Iraq (‫العراق‬‎)', 'calling_code' => '964'],
        'IE' => ['name' => 'Ireland', 'calling_code' => '353'],
        'IM' => ['name' => 'Isle of Man', 'calling_code' => '44'],
        'IL' => ['name' => 'Israel (‫ישראל‬‎)', 'calling_code' => '972'],
        'IT' => ['name' => 'Italy (Italia)', 'calling_code' => '39'],
        'JM' => ['name' => 'Jamaica', 'calling_code' => '1'],
        'JP' => ['name' => 'Japan (日本)', 'calling_code' => '81'],
        'JE' => ['name' => 'Jersey', 'calling_code' => '44'],
        'JO' => ['name' => 'Jordan (‫الأردن‬‎)', 'calling_code' => '962'],
        'KZ' => ['name' => 'Kazakhstan (Казахстан)', 'calling_code' => '7'],
        'KE' => ['name' => 'Kenya', 'calling_code' => '254'],
        'KI' => ['name' => 'Kiribati', 'calling_code' => '686'],
        'KP' => ['name' => 'North Korea (조선 민주주의 인민 공화국)', 'calling_code' => '850'],
        'KR' => ['name' => 'South Korea (대한민국)', 'calling_code' => '82'],
        'XK' => ['name' => 'Kosovo (Kosovë)', 'calling_code' => '381'],
        'KW' => ['name' => 'Kuwait (‫الكويت‬‎)', 'calling_code' => '965'],
        'KG' => ['name' => 'Kyrgyzstan (Кыргызстан)', 'calling_code' => '996'],
        'LA' => ['name' => 'Laos (ລາວ)', 'calling_code' => '856'],
        'LV' => ['name' => 'Latvia (Latvija)', 'calling_code' => '371'],
        'LB' => ['name' => 'Lebanon (‫لبنان‬‎)', 'calling_code' => '961'],
        'LS' => ['name' => 'Lesotho', 'calling_code' => '266'],
        'LR' => ['name' => 'Liberia', 'calling_code' => '231'],
        'LY' => ['name' => 'Libya (‫ليبيا‬‎)', 'calling_code' => '218'],
        'LI' => ['name' => 'Liechtenstein', 'calling_code' => '423'],
        'LT' => ['name' => 'Lithuania (Lietuva)', 'calling_code' => '370'],
        'LU' => ['name' => 'Luxembourg', 'calling_code' => '352'],
        'MO' => ['name' => 'Macao (澳門)', 'calling_code' => '853'],
        'MK' => ['name' => 'Macedonia (FYROM) (Македонија)', 'calling_code' => '389'],
        'MG' => ['name' => 'Madagascar (Madagasikara)', 'calling_code' => '261'],
        'MW' => ['name' => 'Malawi', 'calling_code' => '265'],
        'MY' => ['name' => 'Malaysia', 'calling_code' => '60'],
        'MV' => ['name' => 'Maldives', 'calling_code' => '960'],
        'ML' => ['name' => 'Mali', 'calling_code' => '223'],
        'MT' => ['name' => 'Malta', 'calling_code' => '356'],
        'MH' => ['name' => 'Marshall Islands', 'calling_code' => '692'],
        'MQ' => ['name' => 'Martinique', 'calling_code' => '596'],
        'MR' => ['name' => 'Mauritania (‫موريتانيا‬‎)', 'calling_code' => '222'],
        'MU' => ['name' => 'Mauritius (Moris)', 'calling_code' => '230'],
        'YT' => ['name' => 'Mayotte', 'calling_code' => '262'],
        'MX' => ['name' => 'Mexico (México)', 'calling_code' => '52'],
        'FM' => ['name' => 'Federated States of Micronesia', 'calling_code' => '691'],
        'MD' => ['name' => 'Moldova (Republica Moldova)', 'calling_code' => '373'],
        'MC' => ['name' => 'Monaco', 'calling_code' => '377'],
        'MN' => ['name' => 'Mongolia (Монгол)', 'calling_code' => '976'],
        'ME' => ['name' => 'Montenegro (Crna Gora)', 'calling_code' => '382'],
        'MS' => ['name' => 'Montserrat', 'calling_code' => '1'],
        'MA' => ['name' => 'Morocco (‫المغرب‬‎)', 'calling_code' => '212'],
        'MZ' => ['name' => 'Mozambique (Moçambique)', 'calling_code' => '258'],
        'MM' => ['name' => 'Myanmar (Burma) (မြန်မာ)', 'calling_code' => '95'],
        'NA' => ['name' => 'Namibia (Namibië)', 'calling_code' => '264'],
        'NR' => ['name' => 'Nauru', 'calling_code' => '674'],
        'NP' => ['name' => 'Nepal (नेपाल)', 'calling_code' => '977'],
        'NL' => ['name' => 'Netherlands (Nederland)', 'calling_code' => '31'],
        'NC' => ['name' => 'New Caledonia (Nouvelle-Calédonie)', 'calling_code' => '687'],
        'NZ' => ['name' => 'New Zealand', 'calling_code' => '64'],
        'NI' => ['name' => 'Nicaragua', 'calling_code' => '505'],
        'NE' => ['name' => 'Niger (Nijar)', 'calling_code' => '227'],
        'NG' => ['name' => 'Nigeria', 'calling_code' => '234'],
        'NU' => ['name' => 'Niue', 'calling_code' => '683'],
        'NF' => ['name' => 'Norfolk Island', 'calling_code' => '672'],
        'MP' => ['name' => 'Northern Mariana Islands', 'calling_code' => '1'],
        'NO' => ['name' => 'Norway (Norge)', 'calling_code' => '47'],
        'OM' => ['name' => 'Oman (‫عُمان‬‎)', 'calling_code' => '968'],
        'PK' => ['name' => 'Pakistan (‫پاکستان‬‎)', 'calling_code' => '92'],
        'PW' => ['name' => 'Palau', 'calling_code' => '680'],
        'PS' => ['name' => 'Palestine (‫فلسطين‬‎)', 'calling_code' => '970'],
        'PA' => ['name' => 'Panama (Panamá)', 'calling_code' => '507'],
        'PG' => ['name' => 'Papua New Guinea', 'calling_code' => '675'],
        'PY' => ['name' => 'Paraguay', 'calling_code' => '595'],
        'PE' => ['name' => 'Peru (Perú)', 'calling_code' => '51'],
        'PH' => ['name' => 'Philippines', 'calling_code' => '63'],
        'PN' => ['name' => 'Pitcairn Islands', 'calling_code' => '64'],
        'PL' => ['name' => 'Poland (Polska)', 'calling_code' => '48'],
        'PT' => ['name' => 'Portugal', 'calling_code' => '351'],
        'PR' => ['name' => 'Puerto Rico', 'calling_code' => '1'],
        'QA' => ['name' => 'Qatar (‫قطر‬‎)', 'calling_code' => '974'],
        'RE' => ['name' => 'Réunion (La Réunion)', 'calling_code' => '262'],
        'RO' => ['name' => 'Romania (România)', 'calling_code' => '40'],
        'RU' => ['name' => 'Russia (Россия)', 'calling_code' => '7'],
        'RW' => ['name' => 'Rwanda', 'calling_code' => '250'],
        'BL' => ['name' => 'Saint Barthélemy (Saint-Barthélemy)', 'calling_code' => '590'],
        'SH' => ['name' => 'Saint Helena', 'calling_code' => '290'],
        'KN' => ['name' => 'Saint Kitts and Nevis', 'calling_code' => '1'],
        'LC' => ['name' => 'Saint Lucia', 'calling_code' => '1'],
        'MF' => ['name' => 'Saint Martin (Saint-Martin (partie française))', 'calling_code' => '590'],
        'PM' => ['name' => 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)', 'calling_code' => '508'],
        'VC' => ['name' => 'Saint Vincent and Grenadines', 'calling_code' => '1'],
        'WS' => ['name' => 'Samoa', 'calling_code' => '685'],
        'SM' => ['name' => 'San Marino', 'calling_code' => '378'],
        'ST' => ['name' => 'São Tomé and Príncipe (São Tomé e Príncipe)', 'calling_code' => '239'],
        'SA' => ['name' => 'Saudi Arabia (‫المملكة العربية السعودية‬‎)', 'calling_code' => '966'],
        'SN' => ['name' => 'Senegal (Sénégal)', 'calling_code' => '221'],
        'RS' => ['name' => 'Serbia (Србија)', 'calling_code' => '381'],
        'SC' => ['name' => 'Seychelles', 'calling_code' => '248'],
        'SL' => ['name' => 'Sierra Leone', 'calling_code' => '232'],
        'SG' => ['name' => 'Singapore', 'calling_code' => '65'],
        'SX' => ['name' => 'Sint Maarten', 'calling_code' => '599'],
        'SK' => ['name' => 'Slovakia (Slovensko)', 'calling_code' => '421'],
        'SI' => ['name' => 'Slovenia (Slovenija)', 'calling_code' => '386'],
        'SB' => ['name' => 'Solomon Islands', 'calling_code' => '677'],
        'SO' => ['name' => 'Somalia (Soomaaliya)', 'calling_code' => '252'],
        'ZA' => ['name' => 'South Africa', 'calling_code' => '27'],
        'GS' => ['name' => 'South Georgia and South Sandwich Islands', 'calling_code' => '500'],
        'SS' => ['name' => 'South Sudan (‫جنوب السودان‬‎)', 'calling_code' => '211'],
        'ES' => ['name' => 'Spain (España)', 'calling_code' => '34'],
        'LK' => ['name' => 'Sri Lanka (ශ්‍රී ලංකාව)', 'calling_code' => '94'],
        'SD' => ['name' => 'Sudan (‫السودان‬‎)', 'calling_code' => '249'],
        'SR' => ['name' => 'Suriname', 'calling_code' => '597'],
        'SJ' => ['name' => 'Svalbard and Jan Mayen (Svalbard og Jan Mayen)', 'calling_code' => '47'],
        'SZ' => ['name' => 'Swaziland', 'calling_code' => '268'],
        'SE' => ['name' => 'Sweden (Sverige)', 'calling_code' => '46'],
        'CH' => ['name' => 'Switzerland (Schweiz)', 'calling_code' => '41'],
        'SY' => ['name' => 'Syria (‫سوريا‬‎)', 'calling_code' => '963'],
        'TW' => ['name' => 'Taiwan (台灣)', 'calling_code' => '886'],
        'TJ' => ['name' => 'Tajikistan', 'calling_code' => '992'],
        'TZ' => ['name' => 'Tanzania', 'calling_code' => '255'],
        'TH' => ['name' => 'Thailand (ไทย)', 'calling_code' => '66'],
        'TL' => ['name' => 'Timor-Leste', 'calling_code' => '670'],
        'TG' => ['name' => 'Togo', 'calling_code' => '228'],
        'TK' => ['name' => 'Tokelau', 'calling_code' => '690'],
        'TO' => ['name' => 'Tonga', 'calling_code' => '676'],
        'TT' => ['name' => 'Trinidad and Tobago', 'calling_code' => '1'],
        'TA' => ['name' => 'Tristan da Cunha', 'calling_code' => '290'],
        'TN' => ['name' => 'Tunisia (‫تونس‬‎)', 'calling_code' => '216'],
        'TR' => ['name' => 'Turkey (Türkiye)', 'calling_code' => '90'],
        'TM' => ['name' => 'Turkmenistan', 'calling_code' => '993'],
        'TC' => ['name' => 'Turks and Caicos Islands', 'calling_code' => '1'],
        'TV' => ['name' => 'Tuvalu', 'calling_code' => '688'],
        'UG' => ['name' => 'Uganda', 'calling_code' => '256'],
        'UA' => ['name' => 'Ukraine (Україна)', 'calling_code' => '380'],
        'AE' => ['name' => 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)', 'calling_code' => '971'],
        'GB' => ['name' => 'United Kingdom', 'calling_code' => '44'],
        'US' => ['name' => 'United States', 'calling_code' => '1'],
        'UM' => ['name' => 'U.S. Outlying Islands', 'calling_code' => '1'],
        'VI' => ['name' => 'U.S. Virgin Islands', 'calling_code' => '1'],
        'UY' => ['name' => 'Uruguay', 'calling_code' => '598'],
        'UZ' => ['name' => 'Uzbekistan (Oʻzbekiston)', 'calling_code' => '998'],
        'VU' => ['name' => 'Vanuatu', 'calling_code' => '678'],
        'VA' => ['name' => 'Vatican City (Città del Vaticano)', 'calling_code' => '39'],
        'VE' => ['name' => 'Venezuela', 'calling_code' => '58'],
        'VN' => ['name' => 'Vietnam (Việt Nam)', 'calling_code' => '84'],
        'WF' => ['name' => 'Wallis and Futuna', 'calling_code' => '681'],
        'EH' => ['name' => 'Western Sahara (‫الصحراء الغربية‬‎)', 'calling_code' => '212'],
        'YE' => ['name' => 'Yemen (‫اليمن‬‎)', 'calling_code' => '967'],
        'ZM' => ['name' => 'Zambia', 'calling_code' => '260'],
        'ZW' => ['name' => 'Zimbabwe', 'calling_code' => '263'],
    ],

    'external_links' => [
        'html5shiv' => 'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
        'respond' => 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
        'jquery' => 'https://code.jquery.com/jquery-3.2.0.min.js',
        'jquery-ui' => 'https://code.jquery.com/ui/1.12.1/jquery-ui.min.js',
        'jquery-ui-theme-smoothness' => 'https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css',
        'jquery-ui-bootstrap' => '$.widget.bridge(\'uibutton\', $.ui.button); // Resolve conflict in jQuery UI tooltip with Bootstrap tooltip',
        'bootstrap' => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js',
        'bootstrap-css' => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css',
        'font-awesome-css' => 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css',
        'source-sans-pro-css' => 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,600,600italic,700,700italic,300italic,300&subset=latin,vietnamese,latin-ext',
        'open-sans-css' => 'https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=latin-ext,vietnamese',
        'handlebars' => 'https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.6/handlebars.min.js',
        'handlebars-runtime' => 'https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.6/handlebars.runtime.js',
        'select2-js' => 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js',
        'select2-js-full' => 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js',
        'select2-css' => 'https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css',
        'select2-bootstrap-css' => 'https://cdnjs.cloudflare.com/ajax/libs/select2-bootstrap-theme/0.1.0-beta.6/select2-bootstrap.min.css',
        'gmap3' => 'https://cdn.jsdelivr.net/gmap3/7.2.0/gmap3.min.js',
        'google-maps-js-api' => 'https://maps.googleapis.com/maps/api/js',
        'realtime-co-ortc' => 'http://messaging-public.realtime.co/js/2.1.0/ortc.js',
        'medium-editor-css' => 'http://cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css',
        'medium-editor-theme-default' => 'http://cdn.jsdelivr.net/medium-editor/latest/css/themes/default.min.css',
        'medium-editor-js' => 'http://cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js',
    ],
];
